# Generated by Django 3.0.5 on 2020-05-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.CharField(default='lobby', max_length=256),
            preserve_default=False,
        ),
    ]
