# Generated by Django 3.0.5 on 2020-05-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_remove_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='check', max_length=256),
        ),
    ]
